import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import Link from 'next/link'
export const dynamic = 'force-dynamic'
export default async function EditProduct({ params }: { params: { id: string } }) {
  const supabase = createClient(); const { data: p } = await supabase.from('products').select('*').eq('id',params.id).single()
  if(!p) return <div className="text-white p-8">Not found</div>
  async function save(fd: FormData) { 'use server'; const s=createClient(); await s.from('products').update({name:fd.get('name'),description:fd.get('description'),product_type:fd.get('product_type'),category:fd.get('category'),stock_behavior:fd.get('stock_behavior'),is_active:fd.get('is_active')==='on'}).eq('id',params.id); redirect('/admin/products') }
  return (<div className="max-w-2xl"><div className="flex justify-between items-center mb-8"><h1 className="text-3xl font-bold text-white">Edit</h1><Link href="/admin/products" className="text-gray-400">Cancel</Link></div><form action={save} className="space-y-6 bg-gray-900 p-6 rounded-lg border border-gray-800"><div><label className="block mb-2 text-sm text-gray-400">Name</label><input name="name" defaultValue={p.name} required className="w-full p-2 bg-gray-800 rounded border border-gray-700 text-white"/></div><div><label className="block mb-2 text-sm text-gray-400">Description</label><textarea name="description" defaultValue={p.description||''} rows={4} className="w-full p-2 bg-gray-800 rounded border border-gray-700 text-white"/></div><div className="grid grid-cols-2 gap-4"><div><label className="block mb-2 text-sm text-gray-400">Type</label><select name="product_type" defaultValue={p.product_type} className="w-full p-2 bg-gray-800 rounded border border-gray-700 text-white"><option value="KEY">Key</option><option value="LOGIN">Login</option><option value="SERVICE">Service</option></select></div><div><label className="block mb-2 text-sm text-gray-400">Category</label><select name="category" defaultValue={p.category} className="w-full p-2 bg-gray-800 rounded border border-gray-700 text-white"><option value="ROOT">Root</option><option value="NON_ROOT">Non Root</option><option value="VIP">VIP</option></select></div></div><div><label className="block mb-2 text-sm text-gray-400">Stock</label><select name="stock_behavior" defaultValue={p.stock_behavior} className="w-full p-2 bg-gray-800 rounded border border-gray-700 text-white"><option value="SHOW_OUT_OF_STOCK">Out of Stock</option><option value="ALLOW_PENDING">Pending</option></select></div><div className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={p.is_active} className="w-4 h-4"/><label className="text-gray-300">Active</label></div><button type="submit" className="px-6 py-2 bg-[#0070f3] text-white rounded">Save</button></form></div>)
}